(lang dune 3.24)

(name higl)

(generate_opam_files true)

(source
 (github username/reponame))

(authors "Christopher Sumnicht <csumnicht@berkeley.edu>")

(maintainers "Christopher Sumnicht <csumnicht@berkeley.edu>")

(license LICENSE)

(documentation https://url/to/documentation)

(package
 (name higl)
 (synopsis "A short synopsis")
 (description "A longer description")
 (depends ocaml tgls gg)
 (tags
  ("add topics" "to describe" your project)))
